# Generated by Django 5.2.7 on 2025-10-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselog',
            name='company_name',
            field=models.CharField(blank=True, help_text='Name of the company report purchased/requested', max_length=255),
        ),
    ]
