# Generated by Django 5.2.7 on 2025-10-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchaselog_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselog',
            name='contact_no',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='purchaselog',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
