# Generated by Django 5.2.7 on 2025-10-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchaselog_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='organization',
        ),
    ]
