# Generated by Django 5.2.7 on 2025-11-03 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_purchaselog_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INSTITUTIONAL_EYE', 'Institutional Eye'), ('SPECIALS', 'Specials')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='A unique URL-friendly version of the title. Will be auto-generated.', max_length=255, unique=True)),
                ('publication_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(help_text='The main content of the article. You can use HTML.')),
                ('external_link', models.URLField(blank=True, help_text="Optional: Use for the 'Read our blog here' link.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Select or create tags for this article.', to='api.tag')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
