# Generated by Django 5.2.7 on 2025-10-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_purchaselog_contact_no_purchaselog_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaselog',
            old_name='contact_no',
            new_name='phone_number',
        ),
    ]
