# Generated by Django 5.2.7 on 2025-11-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_tag_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Upload a main image for the article card.', null=True, upload_to='article_images/'),
        ),
    ]
