# Generated by Django 5.2.7 on 2025-10-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_contact_no_purchaselog_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaselog',
            name='phone_number',
        ),
    ]
